#pragma once

#include <Serialization/SerializationUtils.hpp>

#define DK_METADATA_FACTORY_PATTERN							\
static type Create() { return type(); };					\
static type* CreateNew() { return new type(); };			\
template<EExtension ext>									\
static type Create(std::stringstream& sstr) {				\
	type t;													\
	Deserialize<ext>(t, sstr);								\
	return t;												\
}															\
template<EExtension ext>									\
static type* CreateNew(std::stringstream& sstr) {			\
	type* t = new type;										\
	Deserialize<ext>(*t, sstr);								\
	return t;												\
}

#define DK_METADATA_FIELD_SERIALIZATION(...)			\
private:												\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD(__VA_ARGS__)	\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY(__VA_ARGS__)		\
DK_METADATA_SERIALIZE_FIELD_TO_JSON(__VA_ARGS__)		\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD(__VA_ARGS__)		\
DK_METADATA_SERIALIZE_FIELD_TO_INI(__VA_ARGS__)			\
DK_METADATA_DESERIALIZE_INI_TO_FIELD(__VA_ARGS__)		\
public:													\
DK_METADATA_SERIALIZE_FIELDS(__VA_ARGS__)

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON(...)												\
static std::string SerializeToJSON(const type& t, int indent) {									\
std::stringstream sstr;																			\
std::string str(TypeName());																	\
str += ": {\n";																					\
DK_EXPAND(DK_CONCAT(DK_METADATA_SERIALIZE_FIELD_TO_JSON, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
for(int i = 0; i < indent - 1; ++i)																\
		str += '\t';																			\
str += '}';																						\
return str;																						\
}

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD(...)													\
static type& DeserializeJSON(type& t, std::stringstream& sstr) {									\
std::string name;																					\
sstr >> name;																						\
if(name == std::string(TypeName()) + ":"){															\
while (name != "}" && name != "},") {																\
sstr >> name;																						\
DK_EXPAND(DK_CONCAT(DK_METADATA_DESERIALIZE_JSON_TO_FIELD, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
}																									\
}																									\
else																								\
	Logbook::Log(Logbook::EOutput::CONSOLE, nullptr,*/												\
		"Object Name is not the one expected, receive %s instead of %s !!",							\
		name.c_str(), TypeName());*/																\
return t;																							\
}

#define DK_METADATA_SERIALIZE_FIELD_TO_INI(...)													\
static std::string SerializeToINI(const type& t) {												\
std::string str;																				\
((str += '[') += TypeName()) += "]\n";															\
std::stringstream sstr;																			\
DK_EXPAND(DK_CONCAT(DK_METADATA_SERIALIZE_FIELD_TO_INI, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
return str;																						\
}

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD(...)												\
static type& DeserializeINI(type& t, std::stringstream& sstr) {									\
std::string name;																				\
sstr >> name;																					\
if(name == (std::string("[") + TypeName()) + "]"){												\
sstr >> name;																					\
while (name[0] != '[' && !sstr.eof()) {															\
DK_EXPAND(DK_CONCAT(DK_METADATA_DESERIALIZE_INI_TO_FIELD, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
sstr >> name;																					\
}																								\
}																								\
else																							\
	Logbook::Log(Logbook::EOutput::CONSOLE, nullptr,											\
		"Object Name is not the one expected, receive %s instead of %s !!",						\
		name.c_str(), name.size(), ((std::string("[") + TypeName()) + "]").c_str(),				\
		strlen(TypeName()) + 2);																\
return t;																						\
}

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD(...)													\
static void DeserializeBinary(type& t, std::stringstream& sstr) {										\
	DK_EXPAND(DK_CONCAT(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
}

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY(...)														\
static std::string SerializeToBinary(const type& t) {													\
	size_t size = ComputeTotalSize(t);																	\
	std::string data;																					\
	data.reserve(size);																					\
	std::stringstream sstr;																				\
	DK_EXPAND(DK_CONCAT(DK_METADATA_SERIALIZE_FIELD_TO_BINARY, DK_ARGS_N(__VA_ARGS__))(__VA_ARGS__))	\
	return data;																						\
}

#define DK_METADATA_DESERIALIZE_FUNC							\
template<EExtension ext>										\
static type& Deserialize(type& t, std::stringstream& sstr) {	\
	switch (ext) {												\
		case EExtension::BINARY :								\
			DeserializeBinary(t, sstr);							\
			break;												\
		case EExtension::JSON :									\
			DeserializeJSON(t, sstr);							\
			break;												\
		case EExtension::INI :									\
			DeserializeINI(t, sstr);							\
			break;												\
		default:												\
			break;												\
	}															\
	return t;													\
}																\
template<EExtension ext>										\
static type	Deserialize(std::stringstream& sstr) {				\
	type t;														\
	return Deserialize<ext>(t, sstr);							\
}																\

#define DK_METADATA_SERIALIZE_FIELDS(...)														\
template<EExtension ext>																		\
static std::stringstream& Serialize(const type& t, std::stringstream& sstr, int indent = 0) {	\
	switch (ext) {																				\
		case EExtension::BINARY :																\
			sstr << SerializeToBinary(t);														\
			break;																				\
		case EExtension::JSON :																	\
			sstr << SerializeToJSON(t, indent);													\
			break;																				\
		case EExtension::INI :																	\
			sstr << SerializeToINI(t);															\
			break;																				\
		default:																				\
			break;																				\
	}																							\
	return sstr;																				\
}																								\
DK_METADATA_DESERIALIZE_FUNC

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)\
fields::Deserialize<EExtension::BINARY>(t, sstr);

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD0

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD1(fields)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD2(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD1(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD3(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD2(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD4(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD3(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD5(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD4(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD6(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD5(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD7(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD6(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD8(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD7(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD9(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD8(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD10(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD9(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD11(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD10(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD12(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD11(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD13(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD12(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD14(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD13(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD15(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD14(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD16(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD15(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD17(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD16(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD18(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD17(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD19(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD18(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD20(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD19(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD21(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD20(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD22(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD21(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD23(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD22(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD24(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD23(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD25(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD24(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD26(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD25(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD27(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD26(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD28(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD27(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD29(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD28(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD30(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD29(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD31(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD30(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_BINARY_TO_FIELD32(fields, ...)\
DK_METADATA_DESERIALIZE_BINARY_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_BINARY_TO_FIELD31(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)			\
sstr = std::stringstream("");										\
data.append(fields::Serialize<EExtension::BINARY>(t, sstr).str());	\

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY0

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY1(fields)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY2(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY1(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY3(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY2(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY4(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY3(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY5(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY4(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY6(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY5(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY7(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY6(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY8(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY7(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY9(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY8(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY10(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY9(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY11(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY10(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY12(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY11(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY13(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY12(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY14(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY13(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY15(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY14(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY16(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY15(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY17(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY16(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY18(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY17(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY19(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY18(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY20(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY19(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY21(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY20(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY22(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY21(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY23(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY22(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY24(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY23(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY25(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY24(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY26(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY25(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY27(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY26(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY28(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY27(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY29(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY28(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY30(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY29(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY31(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY30(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_BINARY32(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_BINARY_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_BINARY31(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)		\
sstr = std::stringstream("");									\
str.append(fields::Serialize<EExtension::JSON>(t, sstr, indent).str());

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON0

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON1(fields)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON2(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON1(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON3(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON2(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON4(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON3(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON5(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON4(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON6(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON5(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON7(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON6(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON8(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON7(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON9(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON8(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON10(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON9(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON11(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON10(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON12(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON11(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON13(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON12(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON14(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON13(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON15(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON14(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON16(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON15(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON17(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON16(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON18(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON17(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON19(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON18(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON20(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON19(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON21(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON20(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON22(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON21(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON23(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON22(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON24(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON23(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON25(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON24(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON26(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON25(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON27(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON26(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON28(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON27(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON29(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON28(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON30(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON29(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON31(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON30(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_JSON32(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_JSON_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_JSON31(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)		\
if(name == std::string(#fields":")) {							\
sstr >> name;													\
fields::Deserialize<EExtension::JSON>(t, sstr);					\
}

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD0

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD1(fields)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD2(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD1(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD3(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD2(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD4(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD3(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD5(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD4(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD6(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD5(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD7(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD6(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD8(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD7(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD9(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD8(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD10(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD9(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD11(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD10(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD12(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD11(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD13(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD12(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD14(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD13(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD15(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD14(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD16(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD15(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD17(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD16(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD18(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD17(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD19(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD18(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD20(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD19(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD21(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD20(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD22(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD21(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD23(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD22(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD24(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD23(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD25(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD24(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD26(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD25(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD27(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD26(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD28(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD27(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD29(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD28(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD30(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD29(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD31(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD30(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_JSON_TO_FIELD32(fields, ...)\
DK_METADATA_DESERIALIZE_JSON_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_JSON_TO_FIELD31(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)			\
sstr = std::stringstream("");									\
str.append(fields::Serialize<EExtension::INI>(t, sstr).str());

#define DK_METADATA_SERIALIZE_FIELD_TO_INI0

#define DK_METADATA_SERIALIZE_FIELD_TO_INI1(fields)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)

#define DK_METADATA_SERIALIZE_FIELD_TO_INI2(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI1(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI3(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI2(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI4(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI3(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI5(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI4(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI6(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI5(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI7(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI6(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI8(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI7(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI9(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI8(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI10(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI9(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI11(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI10(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI12(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI11(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI13(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI12(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI14(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI13(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI15(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI14(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI16(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI15(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI17(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI16(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI18(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI17(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI19(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI18(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI20(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI19(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI21(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI20(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI22(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI21(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI23(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI22(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI24(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI23(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI25(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI24(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI26(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI25(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI27(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI26(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI28(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI27(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI29(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI28(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI30(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI29(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI31(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI30(__VA_ARGS__))

#define DK_METADATA_SERIALIZE_FIELD_TO_INI32(fields, ...)\
DK_METADATA_SERIALIZE_FIELD_TO_INI_IMPL(fields)	\
DK_EXPAND(DK_METADATA_SERIALIZE_FIELD_TO_INI31(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
if(name == std::string(";"#fields))				\
fields::Deserialize<EExtension::INI>(t, sstr);

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD0

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD1(fields)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD2(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD1(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD3(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD2(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD4(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD3(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD5(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD4(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD6(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD5(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD7(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD6(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD8(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD7(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD9(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD8(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD10(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD9(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD11(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD10(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD12(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD11(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD13(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD12(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD14(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD13(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD15(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD14(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD16(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD15(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD17(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD16(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD18(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD17(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD19(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD18(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD20(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD19(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD21(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD20(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD22(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD21(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD23(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD22(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD24(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD23(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD25(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD24(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD26(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD25(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD27(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD26(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD28(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD27(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD29(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD28(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD30(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD29(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD31(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD30(__VA_ARGS__))

#define DK_METADATA_DESERIALIZE_INI_TO_FIELD32(fields, ...)\
DK_METADATA_DESERIALIZE_INI_TO_FIELD_IMPL(fields)	\
DK_EXPAND(DK_METADATA_DESERIALIZE_INI_TO_FIELD31(__VA_ARGS__))